DROP INDEX "consumer_transaction_proof_id_idx";--> statement-breakpoint
ALTER TABLE "consumer_transaction" ADD CONSTRAINT "consumer_transaction_redemption_request_id_redemption_request_id_fk" FOREIGN KEY ("redemption_request_id") REFERENCES "public"."redemption_request"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "redemption_request" ADD CONSTRAINT "redemption_request_voucher_id_consumer_voucher_id_fk" FOREIGN KEY ("voucher_id") REFERENCES "public"."consumer_voucher"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "consumer_voucher" ADD CONSTRAINT "consumer_voucher_crawl_id_coffee_crawl_id_fk" FOREIGN KEY ("crawl_id") REFERENCES "public"."coffee_crawl"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "consumer_transaction_proof_id_uq" ON "consumer_transaction" USING btree ("proof_id") WHERE "consumer_transaction"."proof_id" IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "consumer_transaction_redemption_request_id_uq" ON "consumer_transaction" USING btree ("redemption_request_id") WHERE "consumer_transaction"."redemption_request_id" IS NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "coffee_crawl_step_crawl_cafe_uq" ON "coffee_crawl_step" USING btree ("crawl_id","cafe_id");--> statement-breakpoint
ALTER TABLE "consumer_transaction" ADD CONSTRAINT "consumer_transaction_operation_shape" CHECK (("consumer_transaction"."operation" = 'emission' AND "consumer_transaction"."proof_id" IS NOT NULL AND "consumer_transaction"."redemption_request_id" IS NULL) OR ("consumer_transaction"."operation" IN ('punch_redemption', 'voucher_redemption') AND "consumer_transaction"."proof_id" IS NULL AND "consumer_transaction"."redemption_request_id" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "consumption_proof" ADD CONSTRAINT "consumption_proof_confirmed_binding" CHECK ("consumption_proof"."status" <> 'confirmed' OR ("consumption_proof"."consumer_user_id" IS NOT NULL AND "consumption_proof"."cafe_signature" IS NOT NULL AND "consumption_proof"."consumer_signature" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "redemption_request" ADD CONSTRAINT "redemption_request_kind_shape" CHECK (("redemption_request"."kind" = 'punch_reward' AND "redemption_request"."product_id" IS NOT NULL AND "redemption_request"."voucher_id" IS NULL) OR ("redemption_request"."kind" = 'voucher' AND "redemption_request"."product_id" IS NULL AND "redemption_request"."voucher_id" IS NOT NULL));--> statement-breakpoint
ALTER TABLE "campaign" ADD CONSTRAINT "campaign_window_order" CHECK ("campaign"."window_start" <= "campaign"."window_end");--> statement-breakpoint
ALTER TABLE "coffee_crawl_step" ADD CONSTRAINT "coffee_crawl_step_index_nonneg" CHECK ("coffee_crawl_step"."step_index" >= 0);--> statement-breakpoint
ALTER TABLE "consumer_voucher" ADD CONSTRAINT "consumer_voucher_source_provenance" CHECK (("consumer_voucher"."source" = 'campaign' AND "consumer_voucher"."campaign_id" IS NOT NULL AND "consumer_voucher"."crawl_id" IS NULL) OR ("consumer_voucher"."source" = 'crawl' AND "consumer_voucher"."campaign_id" IS NULL AND "consumer_voucher"."crawl_id" IS NOT NULL));