import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const contracts: Record<string, string> = {
    cafeRegistry: "CafeRegistry",
    planManager: "PlanManager",
    consumptionLog: "ConsumptionLog",
    punchVault: "PunchVault",
    networkFund: "NetworkFund",
    campaignEscrow: "CampaignEscrow",
    mockPEN: "MockPEN",
};

const outDir = join(import.meta.dirname, "../packages/contracts/out");
const entries = Object.entries(contracts).map(([key, name]) => {
    const artifact = JSON.parse(
        readFileSync(join(outDir, `${name}.sol/${name}.json`), "utf8"),
    );
    return `    ${key}: ${JSON.stringify(artifact.abi)} as const,`;
});

const banner =
    "// GENERATED by scripts/gen-abis.ts — do not edit. Run `pnpm chain:abis`.";
writeFileSync(
    join(import.meta.dirname, "../src/core/chain/abis.ts"),
    `${banner}\nexport const abis = {\n${entries.join("\n")}\n} as const;\n`,
);
console.log("abis.ts written");
